language: java

jdk: oraclejdk8

install: true

before_script:
    - cd ./01_helloWorld/ 
#    - export DISPLAY=:0
#    - unset DISPLAY
script:
    - mvn package -Dmaven.test.skip=true
    - java -jar ./target/CreatiCoding-0.0.1.jar
   #- ./mvnw spring-boot:run
